version = 1

# Files that can't carry an SPDX comment header.
[[annotations]]
path = ["**/*.json", "**/*.md", "**/*.yml", "**/*.toml", ".gitignore", ".github/**", "NOTICE"]
SPDX-FileCopyrightText = "2026 wckdboy and Omnie-dev contributors"
SPDX-License-Identifier = "Apache-2.0"
