// SPDX-FileCopyrightText: 2026 wckdboy and Omnie-dev contributors
// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/gen-theme.swift from brand/tokens.json (version 0.1.0).
// Do not edit by hand. Edit tokens.json and re-run the script.

public extension Palette {
    static let dark = Palette(
        surface: SurfaceColors(
            chrome: RGBA(0x0B0C0EFF),
            editor: RGBA(0x111316FF),
            pane: RGBA(0x16191DFF),
            raised: RGBA(0x1D2126FF),
            hairline: RGBA(0x2A2F36FF),
            selection: RGBA(0x3DD6F533)
        ),
        text: TextColors(
            primary: RGBA(0xE6E8EBFF),
            secondary: RGBA(0xA3AAB4FF),
            tertiary: RGBA(0x7D8590FF)
        ),
        accent: AccentColors(
            ion: RGBA(0x3DD6F5FF),
            agent: RGBA(0xB4A2FFFF),
            focusRing: RGBA(0x3DD6F5FF)
        ),
        status: StatusColors(
            ok: RGBA(0x4ADE80FF),
            warn: RGBA(0xFBBF24FF),
            error: RGBA(0xF87171FF)
        ),
        syntax: SyntaxColors(
            plain: RGBA(0xE6E8EBFF),
            comment: RGBA(0x8B94A1FF),
            punctuation: RGBA(0xA3AAB4FF),
            keyword: RGBA(0xFF9F7AFF),
            string: RGBA(0xB5D98AFF),
            number: RGBA(0xF5C26BFF),
            function: RGBA(0x7FD4F0FF),
            type: RGBA(0x8FB8FFFF)
        ),
        diff: DiffColors(
            addedBg: RGBA(0x123022FF),
            addedWordBg: RGBA(0x1E5A3AFF),
            removedBg: RGBA(0x3A1A1DFF),
            removedWordBg: RGBA(0x6A262CFF)
        )
    )

    static let light = Palette(
        surface: SurfaceColors(
            chrome: RGBA(0xF1F1EFFF),
            editor: RGBA(0xFBFBFAFF),
            pane: RGBA(0xF5F5F3FF),
            raised: RGBA(0xFFFFFFFF),
            hairline: RGBA(0xDADAD6FF),
            selection: RGBA(0x007A9433)
        ),
        text: TextColors(
            primary: RGBA(0x16181BFF),
            secondary: RGBA(0x4E5560FF),
            tertiary: RGBA(0x6B727CFF)
        ),
        accent: AccentColors(
            ion: RGBA(0x007A94FF),
            agent: RGBA(0x6D4FD8FF),
            focusRing: RGBA(0x007A94FF)
        ),
        status: StatusColors(
            ok: RGBA(0x1B7F3BFF),
            warn: RGBA(0x8F5B00FF),
            error: RGBA(0xC62828FF)
        ),
        syntax: SyntaxColors(
            plain: RGBA(0x16181BFF),
            comment: RGBA(0x5F6873FF),
            punctuation: RGBA(0x4E5560FF),
            keyword: RGBA(0xB43E1EFF),
            string: RGBA(0x3F7A1AFF),
            number: RGBA(0x8A5A00FF),
            function: RGBA(0x0A6E8AFF),
            type: RGBA(0x2F55B8FF)
        ),
        diff: DiffColors(
            addedBg: RGBA(0xE3F4E8FF),
            addedWordBg: RGBA(0xBFE6CBFF),
            removedBg: RGBA(0xFBE7E7FF),
            removedWordBg: RGBA(0xF3C4C4FF)
        )
    )

    static let highContrast = Palette(
        surface: SurfaceColors(
            chrome: RGBA(0x000000FF),
            editor: RGBA(0x000000FF),
            pane: RGBA(0x0A0A0AFF),
            raised: RGBA(0x161616FF),
            hairline: RGBA(0x6B6B6BFF),
            selection: RGBA(0x5CE1FF4D)
        ),
        text: TextColors(
            primary: RGBA(0xFFFFFFFF),
            secondary: RGBA(0xD0D4DAFF),
            tertiary: RGBA(0xB8C0CBFF)
        ),
        accent: AccentColors(
            ion: RGBA(0x5CE1FFFF),
            agent: RGBA(0xCDBDFFFF),
            focusRing: RGBA(0xFFFFFFFF)
        ),
        status: StatusColors(
            ok: RGBA(0x6EF09AFF),
            warn: RGBA(0xFFD24DFF),
            error: RGBA(0xFF8A8AFF)
        ),
        syntax: SyntaxColors(
            plain: RGBA(0xFFFFFFFF),
            comment: RGBA(0xB8C0CBFF),
            punctuation: RGBA(0xD0D4DAFF),
            keyword: RGBA(0xFFB59AFF),
            string: RGBA(0xCBEFA0FF),
            number: RGBA(0xFFD98AFF),
            function: RGBA(0x9EE6FFFF),
            type: RGBA(0xB3CEFFFF)
        ),
        diff: DiffColors(
            addedBg: RGBA(0x0F3A22FF),
            addedWordBg: RGBA(0x1F6B40FF),
            removedBg: RGBA(0x4A1418FF),
            removedWordBg: RGBA(0x80242CFF)
        )
    )

}
