#!/usr/bin/env swift
// Generates DesignKit's Swift tokens from design/tokens.json.
// Usage: swift scripts/gen-theme.swift   (run from the repo root)

import Foundation

let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
let input = root.appendingPathComponent("design/tokens.json")
let output = root.appendingPathComponent("Packages/OmnieKit/Sources/DesignKit/Tokens+Generated.swift")

guard let data = try? Data(contentsOf: input),
      let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
      let themes = json["themes"] as? [String: [String: [String: String]]]
else {
    FileHandle.standardError.write("Could not read \(input.path)\n".data(using: .utf8)!)
    exit(1)
}

/// "#RRGGBB" or "#RRGGBBAA" -> "0xRRGGBBAA"
func rgba(_ hex: String) -> String {
    var h = hex.uppercased().replacingOccurrences(of: "#", with: "")
    if h.count == 6 { h += "FF" }
    precondition(h.count == 8, "Bad color \(hex)")
    return "0x" + h
}

// Order of groups and keys must match the memberwise initializers in Palette.swift.
let groups: [(name: String, type: String, keys: [String])] = [
    ("surface", "SurfaceColors", ["chrome", "editor", "pane", "raised", "hairline", "selection"]),
    ("text", "TextColors", ["primary", "secondary", "tertiary"]),
    ("accent", "AccentColors", ["ion", "agent", "focusRing"]),
    ("status", "StatusColors", ["ok", "warn", "error"]),
    ("syntax", "SyntaxColors", ["plain", "comment", "punctuation", "keyword", "string", "number", "function", "type"]),
    ("diff", "DiffColors", ["addedBg", "addedWordBg", "removedBg", "removedWordBg"]),
]

var out = """
// Generated by scripts/gen-theme.swift from design/tokens.json (version \(json["version"] ?? "?")).
// Do not edit by hand. Edit tokens.json and re-run the script.

public extension Palette {

"""

for theme in ["dark", "light", "highContrast"] {
    guard let t = themes[theme] else { fatalError("Missing theme \(theme)") }
    out += "    static let \(theme) = Palette(\n"
    let parts = groups.map { g -> String in
        guard let values = t[g.name] else { fatalError("Missing \(theme).\(g.name)") }
        let args = g.keys.map { k -> String in
            guard let v = values[k] else { fatalError("Missing \(theme).\(g.name).\(k)") }
            return "\(k): RGBA(\(rgba(v)))"
        }
        return "        \(g.name): \(g.type)(\n            " + args.joined(separator: ",\n            ") + "\n        )"
    }
    out += parts.joined(separator: ",\n") + "\n    )\n\n"
}
out += "}\n"

try! out.write(to: output, atomically: true, encoding: .utf8)
print("Wrote \(output.path)")
